### ISSUE TITLE
Arbitrary values in react component does not render the class name in the output CSS

### ISSUE THREAD

**Issue by peterpalkovic** [barvian/fluid-tailwind#9]
Hi @barvian,

**Thank you for this plugin, great work!**

Everything works but I'm having an issue with arbitrary values in a Next.js 14 app and also in a Storybook 8 React project.

```json
"fluid-tailwind": "^0.1.6",
"tailwindcss": "^3.4.3"
```

Inside react component the following does not render the class name in the output CSS:

```html
<div className="~p-[4rem]/[8rem]">Hello</div>
```
or
```html
<div className="~min-[20rem]/lg:~text-base/4xl">Hello</div>
```

However, when used in a CSS file with `@apply`, it works as expected:

input
```html
<div className="test">Hello</div>
```
```css
.test {
	@apply ~p-[2rem]/[8rem];
}
```
output
```css
.test {
  --tw-bg-opacity: 1;
  background-color: rgb(248 113 113/ var(--tw-bg-opacity));
  padding: clamp(2rem, -2.29rem + 10.71vw, 8rem);
}
```
Do you have any idea what the problem could be?

Thank you.
